apiVersion: v1
kind: page
spec:
  id: sR_fqKE
  title: Default page
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: TextField
          name: Test
          props:
            fullWidth: true
            label: Test
            defaultValue: Hello world!
    - component: PageRow
      name: pageRow7
      children:
        - component: Button
          name: button1
    - component: PageRow
      name: pageRow5
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              - test: 1
            columns:
              - field: company
                type: string
              - field: id
                type: string
            rowIdField: test
            density: compact
            dataSource: companies
    - component: PageRow
      name: pageRow3
      children:
        - component: Text
          name: Hi
          props:
            value: How it's going?
    - component: PageRow
      name: pageRow2
      children:
        - component: Button
          name: button
          layout:
            horizontalAlign: start
  queries:
    - name: qrImage
      query:
        function: generateQrCode
        kind: local
      parameters:
        - name: content
          value:
            $$jsExpression: |
              input.value
